using UnityEngine;
using UnityEngine.SceneManagement;
using TMPro;
using UnityEngine.Events;
using System;

public class LevelManager : MonoBehaviour
{
    public static LevelManager Instance { get; private set; }

    [Header("HUD reference")]
    [SerializeField] private GameObject hudCanvas;
    [SerializeField] private TextMeshProUGUI enemyCounterText;
     
    [SerializeField] private GameObject screenLevelComplete;
    [SerializeField] private GameObject warningMenuPanel;
    [SerializeField] private GameObject screenGameOver;

    [Header("Pause UI")]
    [SerializeField] private GameObject pauseMenuPanel;

    [Header("Card Selection")]
    [SerializeField] private CardScreenController cardScreenController;

    public UnityEvent OnEnemyDefeated;

    private int remainingEnemies;

    void Awake()
    {
        Instance = this;
    }
    public void PauseGame()
    {
        Debug.Log("Game Paused");
        hudCanvas.SetActive(false);
        Time.timeScale = 0f;
        pauseMenuPanel.SetActive(true);
        GameManager.Instance.ActivateActionMap(GameInputMap.UI);
    }

    void Start()
    {
        OnEnemyDefeated.AddListener(EnemyDefeated);

        screenLevelComplete.SetActive(false);
        screenGameOver.SetActive(false);
        hudCanvas.SetActive(false);
        cardScreenController.ShowCardSelection();
    }

    void OnDestroy()
    {
        OnEnemyDefeated.RemoveListener(EnemyDefeated);
    }

    void EnemyDefeated()
    {
        remainingEnemies--;

        UpdateHUD();

        if (remainingEnemies == 0)
        {
            CompleteLevel();
        }
    }

    void UpdateHUD()
    {
        enemyCounterText.text = remainingEnemies.ToString();
    }

    public void CompleteLevel()
    {
        GameManager.Instance.ActivateActionMap(GameInputMap.UI);
        warningMenuPanel.SetActive(false);
        screenLevelComplete.SetActive(true);
        Time.timeScale = 0f;        
    }

    public void WarningBackToMenu()
    {
        screenLevelComplete.SetActive(false);
        warningMenuPanel.SetActive(true);
    }

    public void StartLevel()
    {
        hudCanvas.SetActive(true);
        Time.timeScale = 1f;
        GameManager.Instance.ActivateActionMap(GameInputMap.Gameplay);
        int enemyCount = GameObject.FindGameObjectsWithTag("Enemy").Length;
        int bossCount = GameObject.FindGameObjectsWithTag("Boss").Length;
        remainingEnemies = enemyCount + bossCount;

        UpdateHUD();
    }

    public void GoToNextLevel()
    {
        GameManager.Instance.LoadNextLevel();
    }

    public void ActivateGameOver()
    {
        screenGameOver.SetActive(true);
        Time.timeScale = 0f;
        GameManager.Instance.ActivateActionMap(GameInputMap.UI);
    }

    public void CardSelect(CardType cardType)
    {
        GameManager.Instance.playerStats.ApplyPowerUp(cardType);
        cardScreenController.HideCardSelection();

        StartLevel();
    }

    public void GoBackToMenu()
    {
        GameManager.Instance.LoadMainMenu();
    }
}
